# Dockerfile for Game Engine Service
# TODO: Implement Dockerfile based on service structure
# This service will be built using Node.js

# FROM node:20-alpine
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# EXPOSE 5002
# CMD ["npm", "start"]
